version: '3.7'

services:

  web:
    image: nginx 
    ports:
      - "80:80"
    volumes:
      - ./${PROJECT_DIRECTORY}:/${PROJECT_DIRECTORY}
      - ./nginx/conf.d:/etc/nginx/conf.d

  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./${PROJECT_DIRECTORY}:/${PROJECT_DIRECTORY}
    working_dir: /${PROJECT_DIRECTORY}
    user: ${CURRENT_UID}

  db:
    image: mariadb
    volumes:
      - ./${DB_DIRECTORY}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    user: ${CURRENT_UID}

  composer:
    image: composer
    volumes:
      - ./${PROJECT_DIRECTORY}:/${PROJECT_DIRECTORY}
    working_dir: /${PROJECT_DIRECTORY}
    command: composer install
    user: ${CURRENT_UID}

  node:
    image: node:8
    volumes:
      - ./${PROJECT_DIRECTORY}:/${PROJECT_DIRECTORY}
    working_dir: /${PROJECT_DIRECTORY}
    command: bash -c 'yarn && yarn run dev'
    user: ${CURRENT_UID}

  adminer:
    image: adminer
    ports:
      - 8080:8080
    user: ${CURRENT_UID}
